"""Train an explicitly synthetic longitudinal LSTM demonstration.

The supplied CSVs do not contain identifiable repeated patient sequences. This
model therefore learns only from generated synthetic trajectories and must not
be described as trained on real patient continuity records.
"""
from __future__ import annotations

import json
import random
from pathlib import Path

import numpy as np
import torch
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score
from sklearn.model_selection import train_test_split
from torch import nn

ROOT = Path(__file__).resolve().parents[1]
ARTIFACT_DIR = ROOT / "ml" / "artifacts"


def make_sequences(count: int = 320, seed: int = 42) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    sequences = []
    labels = []
    for _ in range(count):
        baseline_bp = rng.normal(118, 8)
        baseline_sugar = rng.normal(7.2, 0.7)
        complication = rng.binomial(1, 0.28)
        progression = rng.normal(3.0 if complication else 0.8, 1.3)
        visits = []
        for visit in range(4):
            systolic_bp = baseline_bp + progression * visit + rng.normal(0, 7)
            blood_sugar = baseline_sugar + progression * visit / 12 + rng.normal(0, 0.45)
            gestational_age = 12 + visit * 7 + rng.normal(0, 0.7)
            visits.append([systolic_bp / 160, blood_sugar / 15, gestational_age / 40, complication])
        sequences.append(visits)
        final_signal = visits[-1][0] * 0.65 + visits[-1][1] * 0.2 + complication * 0.25
        label = int(final_signal >= 0.72)
        if rng.random() < 0.15:
            label = 1 - label
        labels.append(label)
    return np.asarray(sequences, dtype=np.float32), np.asarray(labels, dtype=np.float32)


class ContinuityLSTM(nn.Module):
    def __init__(self, input_size: int = 4, hidden_size: int = 16) -> None:
        super().__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, batch_first=True)
        self.output = nn.Linear(hidden_size, 1)

    def forward(self, values: torch.Tensor) -> torch.Tensor:
        _, (hidden, _) = self.lstm(values)
        return self.output(hidden[-1]).squeeze(1)


def train() -> dict[str, object]:
    random.seed(42)
    np.random.seed(42)
    torch.manual_seed(42)
    values, labels = make_sequences()
    train_values, test_values, train_labels, test_labels = train_test_split(values, labels, test_size=0.2, random_state=42, stratify=labels)
    model = ContinuityLSTM()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
    loss_function = nn.BCEWithLogitsLoss()
    train_tensor = torch.from_numpy(train_values)
    label_tensor = torch.from_numpy(train_labels)
    model.train()
    for _ in range(22):
        optimizer.zero_grad()
        loss = loss_function(model(train_tensor), label_tensor)
        loss.backward()
        optimizer.step()
    model.eval()
    with torch.no_grad():
        probabilities = torch.sigmoid(model(torch.from_numpy(test_values))).numpy()
    predictions = (probabilities >= 0.5).astype(int)
    metrics = {
        "status": "evaluated",
        "accuracy": round(float(accuracy_score(test_labels, predictions)), 4),
        "precision": round(float(precision_score(test_labels, predictions, zero_division=0)), 4),
        "recall": round(float(recall_score(test_labels, predictions, zero_division=0)), 4),
        "f1": round(float(f1_score(test_labels, predictions, zero_division=0)), 4),
        "roc_auc": round(float(roc_auc_score(test_labels, probabilities)), 4),
        "sequence_count": len(values),
        "sequence_length": 4,
        "feature_columns": ["systolic_bp_normalized", "blood_sugar_normalized", "gestational_age_normalized", "previous_complications"],
        "data_provenance": "synthetic longitudinal sequences generated by ml/train_lstm.py",
        "patient_level_split": True,
        "note": "Synthetic research demonstration only; this model was not trained on real linked patient trajectories.",
    }
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    torch.save(model.state_dict(), ARTIFACT_DIR / "lstm_model.pt")
    (ARTIFACT_DIR / "lstm_evaluation.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    return metrics


if __name__ == "__main__":
    print(json.dumps(train(), indent=2))