import { ArrowLeft, CalendarDays, Plus, RefreshCw } from 'lucide-react'
import { FormEvent, useEffect, useState } from 'react'
import { loadMotherTimeline, saveAntenatalVisit, saveDelivery, saveNewborn, savePostnatalVisit, TimelineEvent } from '../services/api'

type ProfileData = Awaited<ReturnType<typeof loadMotherTimeline>>

export default function PatientProfile({ id }: { id: number }) {
  const [profile, setProfile] = useState<ProfileData | null>(null)
  const [form, setForm] = useState({ visit_date: new Date().toISOString().slice(0, 10), gestational_age: '', systolic_bp: '', diastolic_bp: '', blood_sugar: '', previous_complications: false })
  const [message, setMessage] = useState('')
  const [saving, setSaving] = useState(false)
  const [recordMode, setRecordMode] = useState<'antenatal' | 'delivery' | 'newborn' | 'postnatal'>('antenatal')
  const [record, setRecord] = useState<Record<string, string | boolean>>({ visit_date: new Date().toISOString().slice(0, 10) })

  async function refresh() { setProfile(await loadMotherTimeline(id)) }
  useEffect(() => { void refresh().catch(() => setMessage('Unable to load this patient from the API.')) }, [id])
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage('')
    try {
      let result: { message: string }
      if (recordMode === 'antenatal') result = await saveAntenatalVisit(id, { ...form, gestational_age: Number(form.gestational_age) || undefined, systolic_bp: Number(form.systolic_bp) || undefined, diastolic_bp: Number(form.diastolic_bp) || undefined, blood_sugar: Number(form.blood_sugar) || undefined })
      else if (recordMode === 'delivery') result = await saveDelivery(id, { ...record, gestational_age: Number(record.gestational_age) || undefined })
      else if (recordMode === 'newborn') result = await saveNewborn(id, { ...record, birth_weight: Number(record.birth_weight) || undefined, date_of_birth: record.date_of_birth, nicu_required: record.nicu_required === 'true' })
      else result = await savePostnatalVisit(id, { ...record, days_after_delivery: Number(record.days_after_delivery) || undefined, newborn_weight: Number(record.newborn_weight) || undefined })
      setMessage(result.message); await refresh()
    } catch { setMessage('Record could not be saved. Check the fields and API connection.') } finally { setSaving(false) }
  }
  function switchRecord(mode: typeof recordMode) { setRecordMode(mode); setRecord({ visit_date: new Date().toISOString().slice(0, 10), delivery_date: new Date().toISOString().slice(0, 10), date_of_birth: new Date().toISOString().slice(0, 10), newborn_code: '' }) }
  function field(name: string, label: string, type = 'text') { return <label>{label}<input type={type} value={String(record[name] ?? '')} onChange={(event) => setRecord({ ...record, [name]: event.target.value })} required={name === 'newborn_code'} /></label> }
  if (!profile) return <section className="page-section"><div className="empty-state">Loading longitudinal record...</div></section>
  const current = profile.mother.current_prediction
  return <section className="page-section">
    <a className="back-link" href="#patients"><ArrowLeft size={15} /> Back to patients</a>
    <div className="profile-heading"><div><p className="section-kicker">Patient profile · {profile.mother.source_type} record</p><h2>{profile.mother.name}</h2><p>{profile.mother.mother_code} · Age {profile.mother.age ?? 'not recorded'} · {profile.mother.antenatal_visit_count} antenatal visits</p></div><div className={`profile-risk ${current?.risk_level.toLowerCase() || 'unknown'}`}><small>Current model risk</small><strong>{current ? `${Math.round(current.risk_score * 100)}%` : '--'}</strong><span>{current?.risk_level || 'Not analyzed'}</span></div></div>
    {message && <div className="form-message">{message}</div>}
    <div className="profile-grid"><div className="panel timeline-panel"><div className="panel-heading"><div><p className="section-kicker">Continuity timeline</p><h3>Maternal and newborn record history</h3></div><RefreshCw size={17} color="#5f8376" /></div><div className="timeline">{profile.events.map((event: TimelineEvent) => <div className="timeline-event" key={`${event.type}-${event.date}-${event.data.id}`}><span className="timeline-node" /><div className="timeline-content"><div className="timeline-meta"><span><CalendarDays size={14} /> {event.date}</span><span>{event.type}</span></div><strong>{event.type === 'antenatal' ? 'Antenatal visit' : event.type === 'delivery' ? 'Delivery' : event.type === 'newborn' ? `Newborn · ${event.data.newborn_code || 'record'}` : 'Postnatal follow-up'}</strong><div className="event-measures">{event.type === 'antenatal' && <><span>GA <b>{event.data.gestational_age ?? '--'}w</b></span><span>BP <b>{event.data.systolic_bp ?? '--'}/{event.data.diastolic_bp ?? '--'}</b></span><span>Blood sugar <b>{event.data.blood_sugar ?? '--'}</b></span></>}{event.type === 'delivery' && <span>Mode <b>{event.data.delivery_mode || 'Not recorded'}</b></span>}{event.type === 'newborn' && <><span>Sex <b>{event.data.sex || '--'}</b></span><span>Weight <b>{event.data.birth_weight ?? '--'} kg</b></span></>}{event.type === 'postnatal' && <><span>Day <b>{event.data.days_after_delivery ?? '--'}</b></span><span>Weight <b>{event.data.newborn_weight ?? '--'} kg</b></span></>}</div>{event.prediction && <span className={`risk-pill ${event.prediction.risk_level.toLowerCase()}`}>{Math.round(event.prediction.risk_score * 100)}% · {event.prediction.risk_level}</span>}</div></div>)}{profile.events.length === 0 && <div className="empty-state">Add a visit to begin longitudinal monitoring.</div>}</div></div>
      <form className="panel visit-form" onSubmit={submit}><div className="panel-heading"><div><p className="section-kicker">Add record</p><h3>{recordMode === 'antenatal' ? 'New antenatal visit' : recordMode === 'delivery' ? 'Delivery record' : recordMode === 'newborn' ? 'Newborn record' : 'Postnatal follow-up'}</h3></div><Plus size={17} color="#5f8376" /></div><div className="record-switcher">{(['antenatal', 'delivery', 'newborn', 'postnatal'] as const).map((mode) => <button type="button" className={recordMode === mode ? 'selected' : ''} onClick={() => switchRecord(mode)} key={mode}>{mode}</button>)}</div>{recordMode === 'antenatal' ? <><label>Visit date<input type="date" value={form.visit_date} onChange={(event) => setForm({ ...form, visit_date: event.target.value })} required /></label><label>Gestational age (weeks)<input type="number" min="0" max="45" value={form.gestational_age} onChange={(event) => setForm({ ...form, gestational_age: event.target.value })} /></label><div className="form-two"><label>Systolic BP<input type="number" value={form.systolic_bp} onChange={(event) => setForm({ ...form, systolic_bp: event.target.value })} /></label><label>Diastolic BP<input type="number" value={form.diastolic_bp} onChange={(event) => setForm({ ...form, diastolic_bp: event.target.value })} /></label></div><label>Blood sugar<input type="number" step="0.01" value={form.blood_sugar} onChange={(event) => setForm({ ...form, blood_sugar: event.target.value })} /></label><label className="checkbox-label"><input type="checkbox" checked={form.previous_complications} onChange={(event) => setForm({ ...form, previous_complications: event.target.checked })} /> Previous complications recorded</label></> : recordMode === 'delivery' ? <>{field('delivery_date', 'Delivery date', 'date')}{field('gestational_age', 'Gestational age (weeks)', 'number')}{field('delivery_mode', 'Delivery mode')}{field('delivery_place', 'Delivery place')}</> : recordMode === 'newborn' ? <>{field('newborn_code', 'Newborn ID')}{field('date_of_birth', 'Date of birth', 'date')}{field('sex', 'Sex')}{field('birth_weight', 'Birth weight (kg)', 'number')}<label className="checkbox-label"><input type="checkbox" checked={record.nicu_required === 'true'} onChange={(event) => setRecord({ ...record, nicu_required: String(event.target.checked) })} /> NICU required recorded</label></> : <>{field('visit_date', 'Visit date', 'date')}{field('days_after_delivery', 'Days after delivery', 'number')}{field('maternal_bp', 'Maternal BP')}{field('newborn_weight', 'Newborn weight (kg)', 'number')}{field('feeding_status', 'Feeding status')}{field('newborn_condition', 'Newborn condition')}</>}<button className="primary-button" disabled={saving} type="submit">{saving ? 'Saving record...' : 'Save record and update timeline'}</button><small className="form-note">Model output is research/demo decision support, not a medical diagnosis.</small></form></div>
  </section>
}