import { FileText, Printer } from 'lucide-react'
import { useEffect, useState } from 'react'
import { loadMotherTimeline, loadMothers, loadPredictions, MotherRecord, PredictionRecord } from '../services/api'

export default function Reports() {
  const [mothers, setMothers] = useState<MotherRecord[]>([])
  const [selected, setSelected] = useState(3)
  const [profile, setProfile] = useState<Awaited<ReturnType<typeof loadMotherTimeline>> | null>(null)
  const [predictions, setPredictions] = useState<PredictionRecord[]>([])
  useEffect(() => { loadMothers().then(setMothers).catch(() => undefined) }, [])
  useEffect(() => { Promise.all([loadMotherTimeline(selected), loadPredictions(selected)]).then(([timeline, history]) => { setProfile(timeline); setPredictions(history) }).catch(() => setProfile(null)) }, [selected])
  return <section className="page-section report-page"><div className="report-toolbar"><div><p className="section-kicker">Printable record</p><h2>Patient report</h2></div><div className="report-actions"><select value={selected} onChange={(event) => setSelected(Number(event.target.value))}>{mothers.map((mother) => <option value={mother.id} key={mother.id}>{mother.mother_code} · {mother.name}</option>)}</select><button className="primary-button" onClick={() => window.print()}><Printer size={14} /> Print report</button></div></div>{profile ? <div className="report-sheet"><div className="report-title"><FileText size={22} /><div><h3>{profile.mother.name}</h3><p>{profile.mother.mother_code} · Age {profile.mother.age ?? 'not recorded'} · {profile.mother.source_type} record</p></div><span className="source-badge">Research prototype</span></div><div className="report-risk"><small>Current model risk</small><strong>{profile.mother.current_prediction ? `${Math.round(profile.mother.current_prediction.risk_score * 100)}%` : '--'}</strong><span>{profile.mother.current_prediction?.risk_level || 'Not analyzed'}</span></div><div className="report-section"><p className="section-kicker">Care journey</p><h3>Longitudinal timeline</h3>{profile.events.map((event) => <div className="report-event" key={`${event.type}-${event.date}-${event.data.id}`}><strong>{event.type}</strong><span>{event.date}</span><small>{event.type === 'antenatal' ? `Gestational age ${event.data.gestational_age ?? '--'} weeks · BP ${event.data.systolic_bp ?? '--'}/${event.data.diastolic_bp ?? '--'}` : event.type === 'delivery' ? `Delivery mode: ${event.data.delivery_mode || 'not recorded'}` : event.type === 'newborn' ? `Newborn ${event.data.newborn_code || ''} · Birth weight ${event.data.birth_weight ?? '--'} kg` : `Day ${event.data.days_after_delivery ?? '--'} · Newborn weight ${event.data.newborn_weight ?? '--'} kg`}</small></div>)}</div><div className="report-section"><p className="section-kicker">Prediction history</p><h3>Model-estimated risk updates</h3>{predictions.map((prediction) => <div className="report-prediction" key={prediction.id}><span>{new Date(prediction.timestamp).toLocaleString()}</span><strong>{Math.round(prediction.risk_score * 100)}% · {prediction.risk_level}</strong><small>{prediction.model_name}</small></div>)}</div><p className="report-disclaimer">This report is intended for research and educational decision support and is not a medical diagnosis. Review the underlying records with professional judgment.</p></div> : <div className="empty-state">Loading patient report...</div>}</section>
}