import { Activity, ArrowUpRight, CalendarDays } from 'lucide-react'
import { useEffect, useState } from 'react'
import { loadMothers, loadPredictions, MotherRecord, PredictionRecord } from '../services/api'

export default function RiskMonitoring() {
  const [mothers, setMothers] = useState<MotherRecord[]>([])
  const [selected, setSelected] = useState(3)
  const [predictions, setPredictions] = useState<PredictionRecord[]>([])
  const [error, setError] = useState('')
  useEffect(() => { loadMothers().then(setMothers).catch(() => setError('Risk monitoring is unavailable until the API is running.')) }, [])
  useEffect(() => { loadPredictions(selected).then(setPredictions).catch(() => setPredictions([])) }, [selected])
  const ordered = [...predictions].reverse()
  const trend = ordered.length > 1 ? ordered[ordered.length - 1].risk_score - ordered[0].risk_score : 0
  return <section className="page-section"><div className="page-heading"><div><p className="section-kicker">Longitudinal intelligence</p><h2>Risk monitoring</h2><p>Review how model-estimated risk changes as records accumulate.</p></div><span className="source-badge">{predictions[0]?.is_demo_prediction ? 'Demo / simulated inference' : 'Real model inference'}</span></div>{error ? <div className="empty-state error-state">{error}</div> : <><div className="monitor-toolbar panel"><label>Selected patient<select value={selected} onChange={(event) => setSelected(Number(event.target.value))}>{mothers.map((mother) => <option value={mother.id} key={mother.id}>{mother.mother_code} · {mother.name}</option>)}</select></label><div className="trend-summary"><Activity size={18} /><span>Trajectory<strong className={trend > 0 ? 'trend-high' : 'trend-low'}>{trend > 0 ? 'Increasing' : trend < 0 ? 'Decreasing' : 'Stable'}</strong></span></div></div><div className="monitor-grid"><div className="panel risk-history"><div className="panel-heading"><div><p className="section-kicker">Prediction history</p><h3>Risk trajectory</h3></div><span className="text-link">{predictions.length} predictions</span></div>{ordered.length ? <div className="prediction-list">{ordered.map((prediction, index) => <div className="prediction-item" key={prediction.id}><div className="prediction-step"><span>{index + 1}</span><i /></div><div className="prediction-copy"><div><strong>{Math.round(prediction.risk_score * 100)}% · {prediction.risk_level}</strong><small><CalendarDays size={12} /> {new Date(prediction.timestamp).toLocaleString()}</small></div><div className="factor-row">{prediction.factors.slice(0, 3).map((factor) => <span key={factor.feature}>{factor.feature.replaceAll('_', ' ')} <b>+{factor.contribution}</b></span>)}</div></div></div>)}</div> : <div className="empty-state">No prediction history available.</div>}</div><div className="panel explanation-panel"><div className="panel-heading"><div><p className="section-kicker">Latest explanation</p><h3>Why this score?</h3></div><ArrowUpRight size={17} color="#5f8376" /></div>{predictions[0]?.factors.map((factor) => <div className="explanation-row" key={factor.feature}><span>{factor.feature.replaceAll('_', ' ')}</span><strong>+{factor.contribution}</strong><small>{String(factor.value)}</small></div>) || <div className="empty-state">Run an analysis to see feature contributions.</div>}<p className="explanation-note">Feature contribution indicates how a feature influenced this model prediction. It does not establish causation.</p></div></div></>}</section>
}